name: dwp-smart-app
description: DWP Smart Management Application - Laravel + React
version: 1.0.0

build:
  commands:
    - composer install --no-dev --optimize-autoloader --no-interaction
    - npm ci --production=false
    - npm run build
    - mkdir -p storage/logs storage/framework/cache storage/framework/sessions storage/framework/views bootstrap/cache
    - chmod -R 755 storage bootstrap/cache

env:
  APP_NAME: "DWP Smart Management"
  APP_ENV: production
  APP_DEBUG: false
  APP_KEY: "base64:fDyyY5fLH0n78AB+OCJAxG8qN9KR7e3Crsjp0NVJZE0="
  DB_CONNECTION: pgsql
  DB_HOST: turntable.proxy.rlwy.net
  DB_PORT: "37284"
  DB_DATABASE: railway
  DB_USERNAME: postgres
  DB_PASSWORD: tdfJbvddfxeYPMuaLPCWhTHpmZnVZvZk
  SESSION_DRIVER: file
  CACHE_STORE: file
  QUEUE_CONNECTION: sync
  MAIL_MAILER: log
  LOG_LEVEL: error

start:
  cmd: php start.php

volumes:
  - "./storage"
  - "./bootstrap/cache"
