name: dwp-smart-app
kind: web
description: DWP Smart Management Application - Laravel + React

build:
  commands:
    - composer install --no-dev --optimize-autoloader
    - npm ci && npm run build
    - php artisan config:clear
    - php artisan cache:clear
    - php artisan view:clear

start:
  cmd: php -S 0.0.0.0:8080 -t public

env:
  - APP_NAME=DWP Smart Management
  - APP_ENV=production
  - APP_DEBUG=false
  - APP_KEY=base64:fDyyY5fLH0n78AB+OCJAxG8qN9KR7e3Crsjp0NVJZE0=
  - DB_CONNECTION=pgsql
  - DB_HOST=turntable.proxy.rlwy.net
  - DB_PORT=37284
  - DB_DATABASE=railway
  - DB_USERNAME=postgres
  - DB_PASSWORD=tdfJbvddfxeYPMuaLPCWhTHpmZnVZvZk
  - SESSION_DRIVER=file
  - CACHE_STORE=file
  - QUEUE_CONNECTION=sync
  - MAIL_MAILER=log
  - LOG_LEVEL=error

volumes:
  - "./storage:/app/storage"
  - "./bootstrap/cache:/app/bootstrap/cache"
